services:
  ipnotify:
    image: ghcr.io/fasonju/ipnotify:latest
    volumes:
      - "./scripts:/scripts"
    env_file:
      - path: ./.env
    networks:
      - ip6net

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64
