name: Build and publish a Docker image to ghcr.io
on:
  release:
    types: [published]

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: Extract release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: build and push
        run: |
          docker login --username fasonju --password ${{secrets.GH_PAT}} ghcr.io
          docker build \
            --tag ghcr.io/fasonju/ipnotify:latest .
          docker push  ghcr.io/fasonju/ipnotify:latest
          docker push ghcr.io/fasonju/ipnotify:${VERSION}
